import type { Customer } from '../types/Customer';

export const mockCustomers: Customer[] = [
    {
        id: '1',
        name: 'John Smith',
        email: 'john.smith@email.com',
        company: 'Acme Corp',
        status: 'active',
        joinDate: '2023-01-15',
        lastActivity: '2024-01-10',
        totalOrders: 12,
        totalValue: 45600,
    },
    {
        id: '2',
        name: 'Sarah Johnson',
        email: 'sarah.johnson@techstart.com',
        company: 'TechStart Inc',
        status: 'active',
        joinDate: '2023-03-22',
        lastActivity: '2024-01-08',
        totalOrders: 8,
        totalValue: 32400,
    },
    {
        id: '3',
        name: 'Michael Brown',
        email: 'michael.brown@globalco.com',
        company: 'Global Solutions',
        status: 'pending',
        joinDate: '2023-12-01',
        lastActivity: '2024-01-05',
        totalOrders: 3,
        totalValue: 12800,
    },
    {
        id: '4',
        name: 'Emily Davis',
        email: 'emily.davis@innovate.com',
        company: 'Innovate Labs',
        status: 'active',
        joinDate: '2023-06-10',
        lastActivity: '2024-01-09',
        totalOrders: 15,
        totalValue: 67200,
    },
    {
        id: '5',
        name: 'David Wilson',
        email: 'david.wilson@enterprise.com',
        company: 'Enterprise Systems',
        status: 'inactive',
        joinDate: '2022-11-30',
        lastActivity: '2023-12-15',
        totalOrders: 25,
        totalValue: 89500,
    },
    {
        id: '6',
        name: 'Lisa Anderson',
        email: 'lisa.anderson@startup.com',
        company: 'Startup Ventures',
        status: 'active',
        joinDate: '2023-08-14',
        lastActivity: '2024-01-07',
        totalOrders: 6,
        totalValue: 23400,
    },
    {
        id: '7',
        name: 'Robert Taylor',
        email: 'robert.taylor@megacorp.com',
        company: 'MegaCorp Industries',
        status: 'active',
        joinDate: '2023-02-28',
        lastActivity: '2024-01-06',
        totalOrders: 18,
        totalValue: 78900,
    },
    {
        id: '8',
        name: 'Jennifer Martinez',
        email: 'jennifer.martinez@solutions.com',
        company: 'Smart Solutions',
        status: 'pending',
        joinDate: '2023-11-20',
        lastActivity: '2024-01-04',
        totalOrders: 2,
        totalValue: 8600,
    },
    {
        id: '9',
        name: 'Christopher Lee',
        email: 'christopher.lee@dynamics.com',
        company: 'Dynamic Systems',
        status: 'active',
        joinDate: '2023-04-05',
        lastActivity: '2024-01-03',
        totalOrders: 11,
        totalValue: 41200,
    },
    {
        id: '10',
        name: 'Amanda White',
        email: 'amanda.white@future.com',
        company: 'Future Tech',
        status: 'active',
        joinDate: '2023-07-18',
        lastActivity: '2024-01-02',
        totalOrders: 9,
        totalValue: 35700,
    },
]; 